### ISSUE TITLE
Recording-Seeking Crashes Box at x16 or higher

### ISSUE THREAD

**Issue by Beaving** [OpenPLi/enigma2#1904] opened 2018-12-19 22:15 UTC
I wanted to watch a movie that I recorded and seek forward, but when changing seek speed from x8 to x16, the box crashes, or rather, gets an endless spinner. Debug log has nothing interesting:

> [eDVBVideo0] VIDEO_CONTINUE ok
> resolved to FAST FORWARD
> action: seekFwd
> [ActionMap] Keymap 'InfobarSeekActions' -> Action = 'seekFwd'
> [eDVBServicePlay] setFastForward 4
> [eTSMPEGDecoder] decoder state: decoderfastforward, vpid=03ff, apid=0400
> [eDVBVideo0] VIDEO_SLOWMOTION 0 ok
> [eDVBVideo0] VIDEO_FAST_FORWARD 4 ok
> [eDVBVideo0] VIDEO_CONTINUE ok
> resolved to FAST FORWARD
> [eDVBFrontend0] close frontend
> [eDVBFrontend0] sendTone allowed only in feSatellite (1)
> action: seekFwd
> [ActionMap] Keymap 'InfobarSeekActions' -> Action = 'seekFwd'
> [eDVBServicePlay] setFastForward 8
> [eTSMPEGDecoder] decoder state: decoderfastforward, vpid=03ff, apid=0400
> [eDVBVideo0] VIDEO_SLOWMOTION 0 ok
> [eDVBVideo0] VIDEO_FAST_FORWARD 8 ok
> [eDVBVideo0] VIDEO_CONTINUE ok
> resolved to FAST FORWARD
> action: seekFwd
> [ActionMap] Keymap 'InfobarSeekActions' -> Action = 'seekFwd'
> [eDVBServicePlay] setFastForward 16
> [eDVBServicePlay] setFastForward setting cue skipmode to 16
> [eDVBChannel] skipmode ratio is 1440000:90000, bitrate is 3171430 bit/s
> [eDVBChannel] resolved to: 720000 524288
> [eDVBChannel] flush pvr
> [eFilePushThread] waiting for pause
> [eFilePushThread] PAUSED
> [eDVBVideo0] VIDEO_CLEAR_BUFFER ok
> [eDVBChannel] done
> [eTSMPEGDecoder] decoder state: trickmode, vpid=03ff, apid=0400
> [eDVBVideo0] VIDEO_SLOWMOTION 0 ok
> [eDVBVideo0] VIDEO_FAST_FORWARD 1 ok
> [eDVBVideo0] VIDEO_CONTINUE ok
> resolved to FAST FORWARD
> [eDVBChannel] ok, resolved skip (rel: 1, diff 708919), now at           3df970
> [eDVBChannel] pvrEvent evtStopped
> [gRC] main thread is non-idle! display spinner!

After further checking, it seems like the .ts.sc file may be corrupted. After deleting it, seek works fine at any speed, even x128. The .ts.sc file will crash any recording which seeks at x16 or higher, not just the original recording. I have no idea what is inside of a .ts.sc file and why playback is fine at x8 and lower. Maybe you can add some further checks? 

Here is the file: [20181219 0417 - Spiegel Geschichte - Spuren des Krieges_ Der Obersalzberg.ts.zip](https://github.com/OpenPLi/enigma2/files/2696682/20181219.0417.-.Spiegel.Geschichte.-.Spuren.des.Krieges_.Der.Obersalzberg.ts.zip)

**Comment by nautilus7** [comment] 2019-03-19 11:29
I had this issue around the same period you reported it, but it has been fixed since then. I don't know what was the cause or what commit fixed it, though.

**Comment by betacentauri** [comment] 2019-04-09 15:19
Should be fixed with this commit
https://github.com/OpenPLi/enigma2/commit/8c2509e84d2ac0d5a7c8aa197b423348fa3b9b3a

**Closed as completed by betacentauri** 2019-04-09 15:19 UTC
